version: '2.1'

volumes:
  teams-profile:

services:
  teams-room:
    build: ./teams-room
    privileged: true
    network_mode: host
    restart: unless-stopped
    environment:
      TEAMS_URL: "https://teams.microsoft.com/v2/"
      TZ: "UTC"
    volumes:
      - teams-profile:/data/profile
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
